### ISSUE TITLE
Display abnormally

### ISSUE THREAD

**Issue by xwzp** [kobanyan/bullet-train-fish-theme#4]
I have installed  Vim Powerline patched fonts and Input Mono , and then installed this theme by omf install https://github.com/kobanyan/bullet-train-fish-theme.

but it seems can't display correctly. Like following picture.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/10193482/52325056-993fee00-2a1e-11e9-90c7-da856df42218.png">

My OS is  "MacOS Mojave 10.14.3"

I don't know what mistake I made.
Please help me , Thank you !

**Comment by kobanyan** [comment]
Have you changed the Terminal font?
If you use Terminal app, see [this article](http://osxdaily.com/2011/09/02/use-any-font-in-the-mac-os-x-lion-terminal/).
If you use another console application, see the help for that application.
